### ISSUE TITLE
Контроль над плеером теряется при выходе с его экрана, а звук продолжается

### ISSUE THREAD

**Issue by MihaxXx** [aleqsanbr/confirmatio#10]
В данном контексте будет нормально прервать плеер при выходе с экрана техники Медитация, но ситуации когда приложение играет музыку, а её нельзя остановить, не должно быть. Сейчас если выйти с экрана, а потом вернуться, остановить музыку не получится

**Comment by aleqsanbr** [comment]
Решено, коммит 9ebcccf
