### ISSUE TITLE
Проблемы с прокруткой карточек в инфо

### ISSUE THREAD

**Issue by caisilus** [aleqsanbr/confirmatio#3]
- Иногда карточка застревает не по центру экрана (см. скрин ниже)
- Иногда можно прокрутить 2 карточки вместо одной за раз

![image](https://github.com/aleqsanbr/confirmatio/assets/58177893/ea2ed36a-1ea7-4ebd-bceb-8e1cae83f36f)

**Comment by caisilus** [comment]
Отпишите плиз, почему не стали фиксить? Это готовый виджет и тут ничего не сделаешь?

**Comment by Ruslan2806** [comment]
Нет, карточки и их перелистывание мы реализовывали сами. Не пофиксили, потому что не успели
