### ISSUE TITLE
Стилистические недочеты с кнопкой назад

### ISSUE THREAD

**Issue by caisilus** [aleqsanbr/confirmatio#4]
- Обычно её не делают полупрозрачной. У вас её практически не видно
- Она у вас есть только в одном месте приложения. Её лучше либо добавить везде, либо нигде (вполне можно полагаться на системную "назад")
- Её расположение нестандартное для Android (обычно её ставят слева сверху а не справа снизу)

![image](https://github.com/aleqsanbr/confirmatio/assets/58177893/c5944af9-8955-45e4-8d9f-561e422bcc5d)

**Comment by MihaxXx** [comment]
Поддержу, нужно прийти к единому подходу навигации внутри приложения и крайне желательно, чтобы он соответствовал общепринятому на платформе, например, на Android обычно есть стрелка назад в верхней панели с названием экрана - там, где у вас лого
_P.S. Там, если поискать, есть вторая версия кнопки назад на страницах нереализованных тестов._

**Comment by aleqsanbr** [comment]
Убрали эту кнопку
